apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USER: kprahul
  DB_PASSWORD: kprahul143

  MAIL_USERNAME: gohulkp42@gmail.com
  MAIL_PASSWORD: "qdip eeht utno ylkr"

  AUTH_CLIENT_SERVICE_ID: ServiceClient
  AUTH_CLIENT_SERVICE_SECRET: ServiceSecret
  AUTH_CLIENT_PKCE_ID: PKCEClient
  AUTH_CLIENT_AUTH_CODE_ID: AuthCodeClient
  AUTH_CLIENT_AUTH_CODE_SECRET: OneDayOrDayOne
