process.roles=broker,controller
node.id=1

# ? Each listener uses DIFFERENT port
listeners=PLAINTEXT://:9092,EXTERNAL://:9098,CONTROLLER://:9093

# ? Advertised correctly
advertised.listeners=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9098

# ? Mapping
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER

controller.quorum.voters=1@kafka:9093

log.dirs=/var/lib/kafka/data