eureka:
  instance:
    hostname: localhost
    preferIpAddress: true

  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
  pattern:
    console: "${LOGPATTERN_CONSOLE}"

server:
  port: 9092