spring:
  r2dbc:
    # Example (PostgreSQL). Change host/port/db/user/pass to your environment.
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${EXECUTION_DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

  sql:
    init:
      # If you have schema.sql/data.sql and want Spring to run them:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}

      client:
        registration:
          executionservice:
            provider: authserver
            client-id: ${AUTH_CLIENT_SERVICE_ID}
            client-secret: ${AUTH_CLIENT_SERVICE_SECRET}
            authorization-grant-type: client_credentials
            scope: service
        provider:
          authserver:
            issuer-uri: ${AUTH_ISSUER_URI}


app:
  base-url: ${EXECUTION_BASE_URL}
  gateway-url: ${GATEWAY_BASE_URL}


kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  execution:
    topic: ${KAFKA_ACTION_TOPIC}
  result:
    topic: ${KAFKA_ACTION_RESULT_TOPIC}
    group-id: ${KAFAK_EXECUTION_CONSUMER_GROUP}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_BASE_URL}/eureka/


logging:
  level:
    root: ${EXECUTION_LOG_LVL:INFO}
  pattern:
    console: ${LOGPATTERN_CONSOLE}

server:
  port: 9095



