spring:
  cloud:
    gateway:  
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 50s
            
app:
 base-url: ${GATEWAY_BASE_URL}
 client:
  auth-url: ${AUTH_BASE_URL}
  user-url: ${USER_BASE_URL}
  workflow-url: ${WORKFLOW_BASE_URL}
  execution-url: ${EXECUTION_BASE_URL}
  action-url: ${ACTION_BASE_URL}
  config-url: ${CONFIG_BASE_URL}
  eureka-url: ${EUREKA_BASE_URL}
  

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_BASE_URL}/eureka/

logging:
  level:
    root: ${GATEWAY_LOG_LVL:INFO}

  pattern:
    console: ${LOGPATTERN_CONSOLE}

server:
  port: 9093