apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:

  # =========================
  # KAFKA CONFIG
  # =========================
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_USER_REGISTERED_TOPIC: user.registered
  KAFKA_ACTION_TOPIC: action.event
  KAFKA_ACTION_RESULT_TOPIC: action.result

  KAFKA_USER_CONSUMER_GROUP: user-service-group
  KAFKA_ACTION_CONSUMER_GROUP: action-service-group
  KAFKA_EXECUTION_CONSUMER_GROUP: execution-service-group


  # =========================
  # SERVICE COMMUNICATION (INTERNAL DNS)
  # =========================
  AUTH_SERVICE_URL: http://auth-service:9099
  USER_SERVICE_URL: http://user-service:9097
  WORKFLOW_SERVICE_URL: http://workflow-service:9094
  EXECUTION_SERVICE_URL: http://execution-service:9095
  ACTION_SERVICE_URL: http://action-service:9096
  CONFIG_SERVICE_URL: http://config-service:9091
  GATEWAY_SERVICE_URL: http://gateway-service:9093
  EUREKA_BASE_URL: http://eureka-service:9092 #not needed for kubernetes environment

  # =========================
  # AUTH CONFIG
  # =========================
  AUTH_ISSUER_URI: http://auth-service:9099
  AUTH_REDIRECT_URI: https://oauth.pstmn.io/v1/callback


  # =========================
  # DATABASE CONFIG (SHARED)
  # =========================
  DB_HOST: postgres-service
  DB_PORT: "5432"

  AUTH_DB_NAME: auth_db
  USER_DB_NAME: user_db
  WORKFLOW_DB_NAME: workflow_db
  EXECUTION_DB_NAME: execution_db
  ACTION_DB_NAME: action_db


  # =========================
  # MAIL CONFIG (NON-SENSITIVE)
  # =========================
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  MAIL_DEBUG: "true"


  # =========================
  # LOGGING CONFIG
  # =========================
  LOG_LEVEL_ROOT: INFO
  LOG_LEVEL_AUTH: INFO
  LOG_LEVEL_USER: INFO
  LOG_LEVEL_WORKFLOW: INFO
  LOG_LEVEL_EXECUTION: INFO
  LOG_LEVEL_ACTION: INFO

  LOG_PATTERN_CONSOLE: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"


  # =========================
  # FEATURE FLAGS
  # =========================
  SPRING_CLOUD_CONFIG_ENABLED: "true"