spring:
  application:
    name: configserver

  profiles:
    active: native

  cloud:
    config:
      native:
        search-locations: classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: ${CONFIG_LOG_LVL:INFO}
  pattern:
    console: ${LOGPATTERN_CONSOLE:INFO}

server:
  port: 9091
