--DROP SCHEMA public CASCADE;
--CREATE SCHEMA public;

CREATE TABLE IF NOT EXISTS workflow_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE TABLE IF NOT EXISTS workflow_type_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    workflow_type_id BIGINT NOT NULL,
    field_key VARCHAR(100) NOT NULL,
    field_label VARCHAR(150) NOT NULL,
    field_type VARCHAR(50) NOT NULL,
    is_required BOOLEAN NOT NULL,
    default_value TEXT,
    allowed_values TEXT[],
    validation_regex TEXT,
    display_order INTEGER NOT NULL,
    CONSTRAINT fk_workflow_type FOREIGN KEY (workflow_type_id) REFERENCES workflow_type(id) ON DELETE CASCADE,
    CONSTRAINT uq_field_key_per_workflow_type UNIQUE (workflow_type_id, field_key),
    CONSTRAINT uq_field_label_per_workflow_type UNIQUE (workflow_type_id, field_label),
    CONSTRAINT uq_display_order_per_workflow_type UNIQUE (workflow_type_id, display_order)
);

CREATE TABLE IF NOT EXISTS workflow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    workflow_type_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    status VARCHAR(50),
    version INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_workflow_type_ref FOREIGN KEY (workflow_type_id) REFERENCES workflow_type(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS workflow_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    workflow_id BIGINT NOT NULL,
    step_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    step_line INTEGER NOT NULL,
    is_last BOOLEAN NOT NULL,
    step_timeout_in_millis BIGINT,
    CONSTRAINT fk_workflow FOREIGN KEY (workflow_id) REFERENCES workflow(id) ON DELETE CASCADE,
    CONSTRAINT uq_step_code_per_workflow UNIQUE (workflow_id, step_code)
);

CREATE TABLE IF NOT EXISTS workflow_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    step_id BIGINT NOT NULL,
    rule_type VARCHAR(50) NOT NULL,
    rule_config TEXT NOT NULL,
    CONSTRAINT fk_step FOREIGN KEY (step_id) REFERENCES workflow_step(id) ON DELETE CASCADE,
    CONSTRAINT uq_rule_per_step UNIQUE (step_id)
);
